Vagrant.configure("2") do |config|
 config.vm.box = "centos/7"
 config.vm.synced_folder ".", "/vagrant", :nfs      => {:mount_options => ["dmode=777","fmode=666"]}
 # Run command every box create below script install.sh
 config.vm.provision "shell", path: "install.sh"

 # Run command every box create below script install.sh
 #config.vm.provision "shell", path: "install.sh", privileged: false

 config.vm.provider "virtualbox" do |v|
       v.memory = 2048
       v.cpus = 2
 end

 #config.vm.define "docker" do |docker|
    # docker.vm.hostname = "docker01"
     #docker.vm.network "private_network", ip: "172.20.50.11"
#end

 config.vm.define "master" do |master|
     master.vm.hostname = "c1-master1"
     master.vm.network "private_network", ip: "172.20.50.12"
 end


 (1..2).each do |i|
     config.vm.define "c1-node#{i}" do |worker|
         worker.vm.hostname = "c1-node#{i}"
         worker.vm.network "private_network", ip: "172.20.50.2#{i}"
     end
 end
end
