Vagrant.configure("2") do |config|
 config.vm.box = "centos/7"
 config.vm.provision "shell", path: "install.sh", privileged: false

 config.vm.provider "virtualbox" do |v|
       v.memory = 1024
       v.cpus = 1
 end

 config.vm.define "minikube" do |docker|
     docker.vm.hostname = "minikube"
     docker.vm.network "private_network", ip: "172.20.40.11"
 end

end
